# syntax: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Deno

on:
  push:
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - 'bundles/**'
      - 'dev/**'
      - 'readme/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.vscode/**'
      - 'bundles/**'
      - 'dev/**'
      - 'readme/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: ['v1.x']
        node-version: ['16.x']

    name: Deno ${{ matrix.deno }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # install node to run denoify.land
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # install deno to run the test
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}

      - name: Install Dependencies
        run: |
          rm -f package.json
          rm -f package-lock.json
          npm init -y
          npm i -D typescript
          npm i -D denoify
          npm i -D rimraf

      - name: Denoify
        run: |
          node_modules/.bin/rimraf deno_lib
          node_modules/.bin/denoify
          node_modules/.bin/rimraf deno_lib/bundles deno_lib/dev

      - name: Run Tests
        run: |
          deno --version
          deno test --no-check -c tsconfig.deno.json test/deno/**
