name: Feature

on:
  push:
    branches-ignore:
      - main
      - master
    paths-ignore:
      - '.vscode/**'
      - 'bundles/**'
      - 'deno_lib/**'
      - 'dev/**'
      - 'readme/**'
      - '**.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '.vscode/**'
      - 'bundles/**'
      - 'deno_lib/**'
      - 'dev/**'
      - 'readme/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build

      - name: Bundle Package
        run: npm run bundle

      - name: Run Tests
        run: npm test

      - name: Run ESLint
        run: npm run lint

        # Don't publish codecov for feature branches
        # - name: Upload coverage to Codecov
        # uses: codecov/codecov-action@v1
        # env:
        #   CI: true
