# syntax: https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: NodeJS

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '.vscode/**'
      - 'bundles/**'
      - 'deno_lib/**'
      - 'dev/**'
      - 'readme/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 17.x]

    name: Node ${{ matrix.node-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build

      - name: Bundle Package
        run: npm run bundle

      - name: Run Tests
        run: npm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        env:
          CI: true
